test_srv:
  image: emarcs/nginx-git
  ports:
    - 8180:80
  volumes:
    - /srv/git:/srv/git
    - logs:/var/log/nginx
    # if you want to use a custom configuration
    - ./default.conf:/etc/nginx/conf.d/default.conf
